# Generated by Django 5.2 on 2025-05-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResouceUsage',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.AddField(
            model_name='plan',
            name='limits',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='plan',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
