# Generated by Django 5.2 on 2025-05-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobia', '0002_curriculum_created_at_curriculum_curriculum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='status',
            field=models.CharField(blank=True, choices=[('C', 'Complete'), ('I', 'Incomplete')], default='I', max_length=10, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='curriculum',
            field=models.FileField(blank=True, null=True, upload_to='curriculums', verbose_name='Curriculum'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='form_data',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Form Raw Data'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='title',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Title'),
        ),
    ]
