# Generated by Django 5.2 on 2025-05-12 17:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobia', '0003_curriculum_slug_curriculum_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='curriculum',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Curriculum'),
        ),
    ]
