# Generated by Django 5.2 on 2025-05-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobia', '0004_alter_curriculum_curriculum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='title',
            field=models.CharField(blank=True, default='(Sem Nome)', max_length=80, null=True, verbose_name='Title'),
        ),
    ]
